"""Initial schema

Revision ID: 6d7e127560db
Revises: e921201102c9
Create Date: 2025-11-22 18:57:17.920086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d7e127560db'
down_revision: Union[str, Sequence[str], None] = 'e921201102c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('idempotency_key', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'sales', ['idempotency_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sales', type_='unique')
    op.drop_column('sales', 'idempotency_key')
    # ### end Alembic commands ###
